import Foundation

public struct ShortcutMapping: Identifiable, Codable, Equatable {
    public var id = UUID()
    public var title: String
    public var key: String
    public var yabaiCommand: String

    public init(title: String, key: String, yabaiCommand: String) {
        self.title = title
        self.key = key
        self.yabaiCommand = yabaiCommand
    }
}

public struct SKHDConfig: Codable, Equatable {
    public var primaryModifier: String = "alt" // alt = Option

    public var focusLeft: String = "h"
    public var focusDown: String = "j"
    public var focusUp: String = "k"
    public var focusRight: String = "l"

    public var swapLeft: String = "h"
    public var swapDown: String = "j"
    public var swapUp: String = "k"
    public var swapRight: String = "l"

    public var toggleFloat: String = "t"
    public var toggleSplit: String = "e"
    public var balanceSizes: String = "b"
    public var restartYabai: String = "r"

    public init() {}

    /// Generates standard ~/.skhdrc content
    public func generateSkhdrc() -> String {
        var lines: [String] = []
        lines.append("# Generated by YabaiControl")
        lines.append("")
        lines.append("# Focus navigation")
        lines.append("\(primaryModifier) - \(focusLeft) : yabai -m window --focus west")
        lines.append("\(primaryModifier) - \(focusDown) : yabai -m window --focus south")
        lines.append("\(primaryModifier) - \(focusUp) : yabai -m window --focus north")
        lines.append("\(primaryModifier) - \(focusRight) : yabai -m window --focus east")
        lines.append("")
        lines.append("# Window Swap / Reordering")
        lines.append("shift + \(primaryModifier) - \(swapLeft) : yabai -m window --swap west")
        lines.append("shift + \(primaryModifier) - \(swapDown) : yabai -m window --swap south")
        lines.append("shift + \(primaryModifier) - \(swapUp) : yabai -m window --swap north")
        lines.append("shift + \(primaryModifier) - \(swapRight) : yabai -m window --swap east")
        lines.append("")
        lines.append("# Window Toggles & Actions")
        lines.append("\(primaryModifier) - \(toggleFloat) : yabai -m window --toggle float --grid 4:4:1:1:2:2")
        lines.append("\(primaryModifier) - \(toggleSplit) : yabai -m window --toggle split")
        lines.append("\(primaryModifier) - \(balanceSizes) : yabai -m space --balance")
        lines.append("shift + \(primaryModifier) - \(restartYabai) : yabai --restart-service")
        lines.append("")
        lines.append("# Workspaces (1-5)")
        for i in 1...5 {
            lines.append("\(primaryModifier) - \(i) : yabai -m space --focus \(i)")
            lines.append("shift + \(primaryModifier) - \(i) : yabai -m window --space \(i)")
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }
}
