import Foundation

public enum YabaiLayout: String, CaseIterable, Identifiable, Codable {
    case bsp = "bsp"
    case stack = "stack"
    case float = "float"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .bsp: return "BSP (Autotile)"
        case .stack: return "Stack"
        case .float: return "Floating"
        }
    }

    public var iconName: String {
        switch self {
        case .bsp: return "rectangle.split.2x2"
        case .stack: return "square.stack.3d.up"
        case .float: return "macwindow"
        }
    }
}

public enum FocusFollowsMouseMode: String, CaseIterable, Identifiable, Codable {
    case off = "off"
    case autoraise = "autoraise"
    case autofocus = "autofocus"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .off: return "Off"
        case .autoraise: return "Auto-Raise"
        case .autofocus: return "Auto-Focus"
        }
    }
}

public struct YabaiConfig: Codable, Equatable {
    public var layout: YabaiLayout = .bsp
    public var windowGap: Int = 8
    public var topPadding: Int = 8
    public var bottomPadding: Int = 8
    public var leftPadding: Int = 8
    public var rightPadding: Int = 8
    public var autoBalance: Bool = false
    public var splitRatio: Double = 0.5
    public var focusFollowsMouse: FocusFollowsMouseMode = .off
    public var mouseFollowsFocus: Bool = false
    public var windowOpacity: Bool = false
    public var activeOpacity: Double = 1.0
    public var normalOpacity: Double = 0.90
    public var floatingApps: [String] = [
        "System Settings",
        "Calculator",
        "1Password",
        "Archive Utility",
        "QuickTime Player",
        "Finder"
    ]

    public init() {}

    /// Generates standard ~/.yabairc shell script content
    public func generateYabairc() -> String {
        var lines: [String] = []
        lines.append("#!/usr/bin/env sh")
        lines.append("# Generated by YabaiControl")
        lines.append("")
        lines.append("# Layout")
        lines.append("yabai -m config layout \(layout.rawValue)")
        lines.append("")
        lines.append("# Padding & Gaps")
        lines.append("yabai -m config top_padding \(topPadding)")
        lines.append("yabai -m config bottom_padding \(bottomPadding)")
        lines.append("yabai -m config left_padding \(leftPadding)")
        lines.append("yabai -m config right_padding \(rightPadding)")
        lines.append("yabai -m config window_gap \(windowGap)")
        lines.append("")
        lines.append("# Mouse & Focus")
        lines.append("yabai -m config focus_follows_mouse \(focusFollowsMouse.rawValue)")
        lines.append("yabai -m config mouse_follows_focus \(mouseFollowsFocus ? "on" : "off")")
        lines.append("yabai -m config auto_balance \(autoBalance ? "on" : "off")")
        lines.append("yabai -m config split_ratio \(String(format: "%.2f", splitRatio))")
        lines.append("")
        if windowOpacity {
            lines.append("# Opacity")
            lines.append("yabai -m config window_opacity on")
            lines.append("yabai -m config active_window_opacity \(String(format: "%.2f", activeOpacity))")
            lines.append("yabai -m config normal_window_opacity \(String(format: "%.2f", normalOpacity))")
            lines.append("")
        }
        lines.append("# Floating App Rules")
        for app in floatingApps {
            lines.append("yabai -m rule --add app=\"^\(app)$\" manage=off")
        }
        lines.append("")
        lines.append("echo \"yabai configuration loaded successfully\"")
        lines.append("")
        return lines.joined(separator: "\n")
    }
}
